name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]



jobs:
  build-and-push-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Build and Push Image
        run: |
          docker login -u af-south-1@HST3UO9IGTJFZUEUNVLJ -p 17227ec551c29000378c99d9623178792861cb5681a524149158e8c59bc2bd31 swr.af-south-1.myhuaweicloud.com
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/time-service:1.0.0 -f time-service/Dockerfile ./time-service
          docker push swr.af-south-1.myhuaweicloud.com/ralf/time-service:1.0.0



      # - name: Update CAE Image
      #   run: |      
      #     hcloud CAE ExecuteAction \
      #       --X-Environment-ID="$ENV_ID" \
      #       --api_version="v1" \
      #       --application_id="$APP_ID" \
      #       --component_id="$COMPONENT_ID" \
      #       --X-Enterprise-Project-ID="$EPI" \
      #       --kind="Action" \
      #       --project_id="$PROJECT_ID" \
      #       --metadata.name="upgrade" \
      #       --metadata.annotations.version="$VERSION" \
      #       --spec.source.type="code" \
      #       --spec.source.sub_type="GitHub" \
      #       --spec.source.url="$URL" \
      #       --spec.source.code.branch="main" \
      #       --spec.source.code.auth_name="$AUTH_NAME" \
      #       --spec.source.code.namespace="$NAMESPACE" 



